### ISSUE TITLE
Doesn't always work?

### ISSUE THREAD

**Issue by Cyancraft** [legobmw99/BetterThanMending#4] opened 2018-05-22 13:37 UTC
>BetterThanMending-1.1.1.jar
>forge-14.23.3.2691

I have this mod on both server and client, and the mod seemed to work fine, Shift+Left Click was mending my items (I have my mouse buttons reversed) for the first day on the server. However, it has stopped working. I can pick up XP orbs, and mend my items. I can repair them with materials and anvils. Shift+Click is no longer repairing my tools.

I've tried with vanilla and modded tools. I've tried with/without armor on. I've tried with/without items in off-hand. I've even unbound other mods' keybinds that were conflicting with Sneak and/or Use Item.

The mod just simply stopped working.

**Comment by legobmw99** [comment] 2018-05-22 13:40
Can I get a full mod list and, if possible, a video?
What happens if you uninstall my mod, run the game, and then put it back?

**Comment by Cyancraft** [comment] 2018-05-22 13:46
Wow, quick response. I'm impressed!

Modlist can be found on the modpack's Curse page: https://minecraft.curseforge.com/projects/the-adanicx-pack/files/2563337

So, I had died while typing the OP, and after death, the mod worked again. However, going to a different dimension, and back to the Overworld makes the mod stop working.

Now I'm thinking it isn't your mod, as there is a bug within Minecraft where XP disappears when switching dimensions. When I picked up an XP orb, the experience bar updated to reflect my accurate experience count, but I still couldn't use the Sneak+Click until my experience was reset to zero, and I picked up XP orbs again.

**Comment by legobmw99** [comment] 2018-05-22 15:47
I'm having a hard time recreating this issue. I am aware of the existing minecraft bug, but even that doesn't consistently show up for me. That said, I assume that is almost certainly the cause. The mod is almost too simple for the issue to arise from itself.

I'm closing the issue, but if you discover anything more please do comment again

**Closed by legobmw99** 2018-05-22 15:47 UTC
